Moved compilation instructions to the Specification book
epi-project/brane-documentation pull request #8
Opened 2024-06-26 13:45 UTC by Lut99

As suggested in #4.

2024-06-26 15:17 UTC, DanielVoogsgerd requested changes
Two small issues after a quick glance. I will create a PR with a makefile to build it locally as well. It will make it probably a lot easier to find these kind of problems.

But besides that it looks good to me. I really think it helps a lot during the setup phase for most people.

2024-06-26 15:17 UTC, DanielVoogsgerd commented on specification/src/SUMMARY.md
> +- [Compiling binaries](./setup/compilation.md)
This should be `development` instead of `setup`, or the source files should be moved. Both are fine by me.

2024-06-26 15:17 UTC, DanielVoogsgerd commented on user-guide/src/system-admins/installation/proxy-node.md
> +The other way to obtain the images is to compile them yourself. If you want to do so, refer to the [compilation instructions](https://wiki.enablingpersonalizedinterventions.nl/specification/setup/com
Idem.

2024-06-26 15:17 UTC, DanielVoogsgerd commented on user-guide/src/system-admins/installation/worker-node.md
> +The other way to obtain the images is to compile them yourself. If you want to do so, refer to the [compilation instructions](https://wiki.enablingpersonalizedinterventions.nl/specification/setup/com
Idem.

2024-06-26 15:17 UTC, DanielVoogsgerd commented on user-guide/src/scientists/installation.md
> +To compile the binary, refer to the [compilation instructions](https://wiki.enablingpersonalizedinterventions.nl/specification/setup/compilation.html) over at the [Brane: A Specification](https://wik
I think it would be nicer to use relative URLs. Also the same error with setup vs development

2024-06-26 15:17 UTC, DanielVoogsgerd commented on user-guide/src/software-engineers/installation.md
> +To compile the binary, refer to the [compilation instructions](https://wiki.enablingpersonalizedinterventions.nl/specification/setup/compilation.html) over at the [Brane: A Specification](https://wik
Idem.

2024-06-26 15:17 UTC, DanielVoogsgerd commented on user-guide/src/system-admins/installation/branectl.md
> +To compile the binary, refer to the [compilation instructions](https://wiki.enablingpersonalizedinterventions.nl/specification/setup/compilation.html) over at the [Brane: A Specification](https://wik
Idem.

2024-06-26 15:17 UTC, DanielVoogsgerd commented on user-guide/src/system-admins/installation/control-node.md
> +The other way to obtain the images is to compile them yourself. If you want to do so, refer to the [compilation instructions](https://wiki.enablingpersonalizedinterventions.nl/specification/setup/com
Idem.

2024-07-03 13:17 UTC, Lut99 commented
Thanks for looking into it!

The `/setup`-thing is indeed a mistake on my part. Guess I had the mind to change it into `development` and then never looked at the links again.

The relative links is a good idea. I was hesitant to use `/specification`, because I figured it'd translate to `/user-guide/specification`. But it doesn't! At least, served locally (with you Makefile :) ), it works.

---

Ready to merge when you are.

2024-07-03 13:40 UTC, DanielVoogsgerd commented
Yeah should be good, feel free to.

2024-07-03 15:12 UTC, merged